### PR TITLE
add v2 torrent creation script

### PR DESCRIPTION
**Pull request by ssiloti**

### CODE REVIEW

**Comment by the8472** [comment]
For the hybrid format in multi-file mode it would make sense to add another padding file at the end so. This allows torrents to be assembled from smaller torrents without rehashing. It's mostly relevant for torrent feeds.

**Comment by the8472** [comment]
```
$ ls -lR test
test:
total 196
-rw-r--r-- 1 the8472 the8472 196605 May 13 06:20 a
-rw-r--r-- 1 the8472 the8472   1024 May 13 06:20 b
drwxr-xr-x 1 the8472 the8472      4 May 13 06:50 dir

test/dir:
total 64
-rw-r--r-- 1 the8472 the8472     0 May 13 06:50 c
-rw-r--r-- 1 the8472 the8472 65536 May 13 06:51 d

$ python bep_0052_torrent_creator.py test
Traceback (most recent call last):
  File "bep_0052_torrent_creator.py", line 239, in <module>
    open(t.name + '.torrent', 'wb').write(encode(t.create(args.tracker, args.v2_only)))
  File "bep_0052_torrent_creator.py", line 226, in create
    return {b'announce': tracker, b'info': info, b'piece layers': {f.root: f.piecesv2 for f in self.piece_layers if hasattr(f, 'piecesv2')}}
  File "bep_0052_torrent_creator.py", line 226, in <dictcomp>
    return {b'announce': tracker, b'info': info, b'piece layers': {f.root: f.piecesv2 for f in self.piece_layers if hasattr(f, 'piecesv2')}}
AttributeError: 'FileHasher' object has no attribute 'root'
```

**Comment by the8472** [comment]
Directory listings in filesystems are not guaranteed to be sorted (it's `ls` that sorts)

```
$ ls -AUlR test
test:
total 196
-rw-r--r-- 1 the8472 the8472 196605 May 13 06:20 a
-rw-r--r-- 1 the8472 the8472   1024 May 13 06:20 b
drwxr-xr-x 1 the8472 the8472      8 May 13 20:01 dir

test/dir:
total 64
-rw-r--r-- 1 the8472 the8472     0 May 13 06:50 c
-rw-r--r-- 1 the8472 the8472 65536 May 13 06:51 d
-rw-r--r-- 1 the8472 the8472     0 May 13 20:01 01
```

This results in the v1 list to be in encounter order while the file tree is sorted per bencoding. Which leads to an invalid hybrid torrent.

`filesld6:lengthi196605e4:pathl1:aeed6:lengthi3e4:pathl4:.pad1:3eed6:lengthi1024e4:pathl1:beed6:lengthi64512e4:pathl4:.pad5:64512eed6:lengthi0e4:pathl3:dir1:ceed6:lengthi65536e4:pathl3:dir1:deed6:lengthi0e4:pathl3:dir2:01eee`

Also, the last v1 file still does not seem to be padded to a full piece size.

**Comment by ssiloti** [comment]
In that case the last file is empty. Why would padding be needed for an empty file?

**Comment by the8472** [comment]
The one before it is not empty and yet not padded.

**Comment by ssiloti** [comment]
The default piece size is 64KB, so assuming you didn't change it that file doesn't need to be padded.

**Comment by the8472** [comment]
Oh duh. Off by one. I intended to make it 1 longer than the piece size.

**Comment by the8472** [comment]
Although the  `attr: p` is missing from the padding files.

**Comment by the8472** [comment]
another small issue

* `python bep_0052_torrent_creator.py test/` results in a 0-length name
* `python bep_0052_torrent_creator.py test` works fine

**Pull request merged**
